const MODULE = 'BOOKING';
export const LIST_REQUEST = `LIST_${MODULE}_REQUEST`;
export const LIST_SUCCESS = `LIST_${MODULE}_SUCCESS`;
export const LIST_FAILURE = `LIST_${MODULE}_FAILURE`;

export const CONFIRM_REQUEST = `CONFIRM_${MODULE}_REQUEST`;
export const CONFIRM_SUCCESS = `CONFIRM_${MODULE}_SUCCESS`;
export const CONFIRM_FAILURE = `CONFIRM_${MODULE}_FAILURE`;

export const REJECT_REQUEST = `REJECT_${MODULE}_REQUEST`;
export const REJECT_SUCCESS = `REJECT_${MODULE}_SUCCESS`;
export const REJECT_FAILURE = `REJECT_${MODULE}_FAILURE`;

export const GET_REQUEST = `GET_${MODULE}_REQUEST`;
export const GET_SUCCESS = `GET_${MODULE}_SUCCESS`;
export const GET_FAILURE = `GET_${MODULE}_FAILURE`;

export const DELETE_REQUEST = `DELETE_${MODULE}_REQUEST`;
export const DELETE_SUCCESS = `DELETE_${MODULE}_SUCCESS`;
export const DELETE_FAILURE = `DELETE_${MODULE}_FAILURE`;

/* Reports */

export const GET_REPORT_REQUEST = `GET_${MODULE}_REPORT_REQUEST`;
export const GET_REPORT_SUCCESS = `GET_${MODULE}_REPORT_SUCCESS`;
export const GET_REPORT_FAILURE = `GET_${MODULE}_REPORT_FAILURE`;
