const MODULE = 'CITY';
export const DROP_DOWN_LIST_REQUEST = `DROP_DOWN_LIST_${MODULE}_REQUEST`;
export const DROP_DOWN_LIST_SUCCESS = `DROP_DOWN_LIST_${MODULE}_SUCCESS`;
export const DROP_DOWN_LIST_FAILURE = `DROP_DOWN_LIST_${MODULE}_FAILURE`;
