const MODULE = 'CATERING';
export const LIST_REQUEST = `LIST_${MODULE}_REQUEST`;
export const LIST_SUCCESS = `LIST_${MODULE}_SUCCESS`;
export const LIST_FAILURE = `LIST_${MODULE}_FAILURE`;

export const SAVE_REQUEST = `SAVE_${MODULE}_REQUEST`;
export const SAVE_SUCCESS = `SAVE_${MODULE}_SUCCESS`;
export const SAVE_FAILURE = `SAVE_${MODULE}_FAILURE`;

export const GET_REQUEST = `GET_${MODULE}_REQUEST`;
export const GET_SUCCESS = `GET_${MODULE}_SUCCESS`;
export const GET_FAILURE = `GET_${MODULE}_FAILURE`;

export const DELETE_REQUEST = `DELETE_${MODULE}_REQUEST`;
export const DELETE_SUCCESS = `DELETE_${MODULE}_SUCCESS`;
export const DELETE_FAILURE = `DELETE_${MODULE}_FAILURE`;

export const DROP_DOWN_LIST_REQUEST = `DROP_DOWN_LIST_${MODULE}_REQUEST`;
export const DROP_DOWN_LIST_SUCCESS = `DROP_DOWN_LIST_${MODULE}_SUCCESS`;
export const DROP_DOWN_LIST_FAILURE = `DROP_DOWN_LIST_${MODULE}_FAILURE`;